name: linux

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

jobs:
  build:
    env:
      VCPKG_ROOT: /tmp/vcpkg

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: >-
        sudo apt-get install clang-tidy-15 cppcheck gcc-12 git curl zip unzip tar -y -q
        
        git clone https://github.com/microsoft/vcpkg $VCPKG_ROOT
        $VCPKG_ROOT/bootstrap-vcpkg.sh -disableMetrics

    - name: Configure
      run: cmake --preset ci-debian

    - name: Build
      run: cmake --build build --config Release -j 2 build/ci

    - name: Test
      working-directory: build/ci
      run: ctest --output-on-failure --no-tests=error -C Release -j 2