name: linux

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      VCPKG_ROOT: /tmp/vcpkg

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get install clang-tidy-15 cppcheck gcc-12 g++-12 git curl zip unzip tar ninja-build -y -q
        echo $VCPKG_ROOT
        
        git clone https://github.com/microsoft/vcpkg $VCPKG_ROOT
        $VCPKG_ROOT/bootstrap-vcpkg.sh -disableMetrics

    - name: Configure
      run: cmake --preset ci-debian

    - name: Build
      run: cmake --build build/ci --config Release -j 2

    - name: Test
      working-directory: build/ci
      run: ctest --output-on-failure --no-tests=error -C Release -j 2